//
//  Data.swift
//  MoodOfTheDay
//
//  Created by Dustin Newman on 2/4/18.
//  Copyright © 2018 Dustin Newman. All rights reserved.
//

import Foundation

let m_songs: [String] = ["Shape of You",
                         "Despacito - Remix",
                         "Something Just Like This",
                         "Grateful",
                         "I'm the One",
                         "HUMBLE.",
                         "It Ain't Me",
                         "Unforgettable",
                         "That's What I Like",
                         "I Don't Wanna Live Forever (Fifty Shades Darker)",
                         "XO TOUR Llif3",
                         "Paris",
                         "Stay",
                         "Attention",
                         "Mask Off",
                         "Congratulations",
                         "Swalla (feat. Nicki Minaj & Ty Dolla $ign)",
                         "Castle on the Hill",
                         "Rockabye (feat. Sean Paul & Anne-Marie)",
                         "Believer",
                         "Mi Gente",
                         "Thunder",
                         "There's Nothing Holdin' Me Back",
                         "Issues",
                         "Galway Girl",
                         "Scared to Be Lonely",
                         "Closer",
                         "Symphony (feat. Zara Larsson)",
                         "Starboy",
                         "Wild Thoughts",
                         "Slide",
                         "New Rules",
                         "1-800-273-8255",
                         "Passionfruit",
                         "rockstar",
                         "Strip That Down",
                         "2U",
                         "Perfect",
                         "Call on Me - Ryan Riback Remix",
                         "Feels",
                         "Felices los 4",
                         "Location",
                         "El Dorado",
                         "Bad and Boujee (feat. Lil Uzi Vert)",
                         "Havana",
                         "Solo Dance",
                         "Fake Love",
                         "Let Me Love You",
                         "One Dance",
                         "SUBEME LA RADIO",
                         "Pretty Girl - Cheat Codes X CADE Remix",
                         "Tell Me You Love Me",
                         "Sorry Not Sorry",
                         "Redbone",
                         "24K Magic",
                         "DNA.",
                         "You Don't Know Me",
                         "Chained To The Rhythm",
                         "No Promises (feat. Demi Lovato)",
                         "Don't Wanna Know (feat. Kendrick Lamar)",
                         "How Far I'll Go - From \"Moana\"", "Slow Hands",
                         "Bounce Back",
                         "Sign of the Times",
                         "goosebumps",
                         "Young Dumb & Broke",
                         "There for You",
                         "Cold (feat. Future)",
                         "Silence",
                         "Too Good At Goodbyes",
                         "Just Hold On",
                         "Look What You Made Me Do",
                         "Glorious (feat. Skylar Grey)",
                         "Starving",
                         "Weak",
                         "Side To Side",
                         "I Like Me Better",
                         "In the Name of Love",
                         "Cold Water",
                         "Malibu",
                         "All Night",
                         "Your Song",
                         "Ahora Dice",
                         "Friends (with BloodPop)",
                         "Bank Account",
                         "Bad Things (with Camila Cabello)",
                         "Don't Let Me Down",
                         "Body Like A Back Road",
                         "Now Or Never",
                         "Dusk Till Dawn",
                         "End Game",
                         "Finesse",
                         "No Limit",
                         "MotorSport"]

let m_foods: [String] = ["Chicken & Rice Soup", "Italian Minestrone Soup", "Spicy Red Lentil Soup",
                         "Creamy Fettuccine w/ Shrimp",
                         "Fettuccini Alfredo",
                         "Portuguese Roast Garlic Chicken",
                         "Smoked Salmon Pancake",
                         "Basmati Rice & Fava Beans w/ Minted Yogurt",
                         "Chickpea Salad w/ Citrus & Celery",
                         "Mediterranean Tomato & Cucumber Chopped Salad",
                         "Middle Eastern Artichoke Salad",
                         "Eggplant Caponata",
                         "Hummus",
                         "Smoked Mozzarella Spread",
                         "Tzatziki Sauce",
                         "Feta Cheese",
                         "Green Pitted Olives",
                         "Kalamata Olives",
                         "Marinated  Olives",
                         "Tomato Basil Pizza",
                         "Cheese Pizza",
                         "Pepperoni Pizza",
                         "Caesar Salad",
                         "Italian Antipasto Salad",
                         "Artichoke, Mushroom, & Fontina Grilled Sandwich",
                         "French Bistro Burger",
                         "Garlic Herb Parmesan Fries",
                         "Marsala Chicken Breast",
                         "Portobello Mushroom Chicken Sandwich",
                         "Shoestring Fries",
                         "Sweet Potato Fries",
                         "Crusty Gruyere Grilled Cheese Sandwich w/ Bacon",
                         "Crusty Gruyere Grilled Cheese Sandwich",
                         "Smoked Chicken Sausage Grilled Cheese",
                         "Veggie Burger",
                         "Cous Cous w/ Raisins & Almonds",
                         "Roasted Fingerling Potato",
                         "Roasted Gold & Red Beets",
                         "Steamed Carrots",
                         "Anise Biscotti",
                         "Blackberry/Peach Crisp",
                         "Butterscotch Chip Cookies",
                         "Chocolate Banana Walnut Bread Pudding",
                         "Chocolate Ganache Cake",
                         "Congo Bars w/ Pecans",
                         "Pumpkin Pie",
                         "Beef & Sweet Potato Soup",
                         "Spicy Red Lentil Soup",
                         "Grilled Pork & Sweet Potato Puree",
                         "Seitan w/ Brown Rice, Kale, Carrot & Peanut Bowl",
                         "Chile Roasted Turkey w/ Jalapeno-Lime Slaw",
                         "Lentils w/ Roasted Beets & Carrots",
                         "Sauteed Rainbow Swiss Chard",
                         "Tri-Color Quinoa",
                         "Roasted Cauliflower",
                         "Roasted Fresh Carrots & Onions",
                         "Green Goddess Flatbread",
                         "Spinach & Artichoke Flatbread",
                         "Roasted Mahi Mahi w/ Tomatillo Sauce",
                         "Grilled Mole Tofu",
                         "Baked Red Rose Potato",
                         "Blood Oranges",
                         "Kiwi",
                         "Pineapple",
                         "Red Grapes",
                         "7 Grain Bread",
                         "Cranberry Cupcake",
                         "Cranberry Walnut Loaf",
                         "Whole Wheat Levain Bread",
                         "Almond Cashew Butter",
                         "Black Pepper-Strawberry Compote",
                         "Chocolate Peanut Butter",
                         "Country Wheat Bread",
                         "Mango Lime Bread",
                         "Pineapple Compote",
                         "Spiced Gingerbread",
                         "Blueberries",
                         "Lowfat Greek Yogurt",
                         "Mango",
                         "Cherry Lime Water",
                         "Grilled Nopales",
                         "Grilled Radishes w/ Lime & Cotija",
                         "Grilled Tri-color Carrots w/ Peruvian Salsa Verde",
                         "Roasted Broccoli",
                         "Black Eyed Pea Chile Verde w/ Smoked Ham Hock",
                         "Cajun Shrimp & Quinoa Casserole",
                         "Oven Roasted Turkey",
                         "Breadsticks",
                         "Brussels Sprouts w/ Chorizo",
                         "Creamed Kale",
                         "Crispy Smashed Potatoes w/ Habanero Aioli",
                         "Southwest Cheese Grits",
                         "Hearty Turkey & Vegetable Soup",
                         "Potato Leek Soup",
                         "Linguini w/ Scallops & Lobster Sauce",
                         "Linguine w/ Quatro Fromaggio",
                         "Honey Roasted Chicken",
                         "Four Cheese Lasagna",
                         "BBQ Blackened Chicken Pizza",
                         "Cheese Pizza",
                         "Pepperoni Pizza",
                         "Bruin Burger",
                         "Bruin Cheeseburger",
                         "White Wine Chicken Breast",
                         "White Wine Chicken Sandwich",
                         "All Turkey Corn Dog",
                         "Multi Veggie Burger",
                         "Shoestring Fries",
                         "Smoked Gouda Grill Cheese",
                         "Blackberry/Peach Crisp",
                         "Butterscotch Chip Cookies",
                         "Chocolate Banana Walnut Bread Pudding",
                         "Chocolate Ganache Cake",
                         "Churro",
                         "Congo Bars w/ Pecans",
                         "Oreo Mousse",
                         "Pumpkin Pie",
                         "Malt-O-Meal",
                         "Oatmeal",
                         "Italian Minestrone Soup",
                         "Spicy Red Lentil Soup",
                         "Egg White",
                         "Omelet Bar",
                         "Bacon",
                         "Chicken Apple Sausage",
                         "Fried Egg Whites",
                         "Fried Eggs",
                         "Potatoes O'Brien",
                         "Scrambled Eggs",
                         "Rigatoni Pomodoro",
                         "Tomato Basil Pizza",
                         "Cheese Pizza",
                         "Pepperoni Pizza",
                         "Caesar Salad",
                         "Italian Antipasto Salad",
                         "Belgian Waffle",
                         "Pancakes",
                         "French Bistro Burger",
                         "Marsala Chicken Breast",
                         "Portobello Mushroom Chicken Sandwich",
                         "Tator Tots",
                         "Crusty Gruyere Grilled Cheese Sandwich",
                         "Veggie Burger",
                         "Biscuit",
                         "Country Sausage Gravy",
                         "Sticky Rice",
                         "Assorted Streudel Sticks",
                         "Banana Walnut Muffin",
                         "Blueberry Muffin",
                         "Chocolate Croissant",
                         "Chocolate Glazed Donut",
                         "Cinnamon Streusel Coffee Cake",
                         "Maple Bar",
                         "Mocha Chocolate Chip Muffin",
                         "Anise Biscotti",
                         "Blackberry/Peach Crisp",
                         "Butterscotch Chip Cookies",
                         "Chocolate Banana Walnut Bread Pudding",
                         "Congo Bars w/ Pecans",
                         "Pecan Pie",
                         "Pumpkin Pie",
                         "Oatmeal",
                         "Chicken & Rice Soup",
                         "Spicy Red Lentil Soup",
                         "Egg White",
                         "Omelet Bar",
                         "Ground Beef, Farro & Mushroom Wrap",
                         "Scrambled Egg Whites",
                         "Scrambled Eggs",
                         "BBQ Pork Tortilla Pizza",
                         "Caramelized Onion Flatbread",
                         "Banana-Pecan Buckwheat Pancake",
                         "Grilled Chicken - Lemon-Ginger Marinade",
                         "Blood Oranges",
                         "Grapefruit",
                         "Kiwi",
                         "Pineapple",
                         "Red Grapes",
                         "7 Grain Bread",
                         "Cranberry Walnut Loaf",
                         "Pistachio Bread",
                         "Vegan Brownie",
                         "Vegan Pumpkin Walnut Bread",
                         "Whole Wheat Levain Bread",
                         "Almond Cashew Butter",
                         "Blueberry Compote",
                         "Cacao Butter",
                         "Chocolate Peanut Butter",
                         "Plantain Butter",
                         "Blueberries",
                         "Cottage Cheese",
                         "Lowfat Greek Yogurt",
                         "Mango",
                         "Lemon-Mint Water",
                         "Biscuit",
                         "Brown Rice",
                         "Country Gravy",
                         "Grilled Nopales",
                         "Grilled Radishes w/ Lime & Cotija",
                         "Grilled Tri-color Carrots w/ Peruvian Salsa Verde",
                         "Roasted Broccoli",
                         "Oven Roasted Turkey",
                         "Breadsticks",
                         "Brussels Sprouts w/ Chorizo",
                         "Creamed Kale",
                         "Crispy Smashed Potatoes w/ Habanero Aioli",
                         "Southwest Cheese Grits",
                         "Grits",
                         "Oatmeal",
                         "Hearty Turkey & Vegetable Soup",
                         "Potato Leek Soup",
                         "Egg White",
                         "Omelet Bar",
                         "Scrambled Egg Whites",
                         "Bacon",
                         "Grilled Hot Links",
                         "Potatoes O'Brien",
                         "Fried Eggs",
                         "Cheese Pizza",
                         "Pepperoni Pizza",
                         "Belgian Waffle",
                         "Eggs Benedict",
                         "Bruin Burger",
                         "Bruin Cheeseburger",
                         "Buffalo Chicken Breast",
                         "Buffalo Chicken Sandwich",
                         "Hash Brown Patty",
                         "Multi Veggie Burger",
                         "Assorted Streudel Sticks",
                         "Banana Walnut Muffin",
                         "Blueberry Muffin",
                         "Chocolate Croissant",
                         "Chocolate Glazed Donut",
                         "Cinnamon Streusel Coffee Cake",
                         "Maple Bar",
                         "Mocha Chocolate Chip Muffin",
                         "Blackberry/Peach Crisp",
                         "Butterscotch Chip Cookies",
                         "Chocolate Ganache Cake",
                         "Churro",
                         "Congo Bars w/ Pecans",
                         "Greek Cream of Roasted Garlic & Cauliflower Soup",
                         "Hearty Italian Soup",
                         "Italian Minestrone Soup",
                         "Pappardelle w/ Garlic Chicken",
                         "Pappardelle w/ Garlic Sauce",
                         "Lamb Keftedes Pita",
                         "Traditional Falafel",
                         "Mediterranean Tomato & Cucumber Chopped Salad",
                         "Middle Eastern Artichoke Salad",
                         "Moroccan CousCous Almond Salad",
                         "Moroccan Sweet & Spicy Eggplant",
                         "Baba Ghannouj",
                         "Carrot Harissa Hummus",
                         "Smoked Salmon Mousse",
                         "Tabouli Salad",
                         "Feta Cheese",
                         "Green Pitted Olives",
                         "Kalamata Olives",
                         "Marinated  Olives",
                         "Meatball Pizza",
                         "Cheese Pizza",
                         "Pepperoni Pizza",
                         "Caesar Salad",
                         "Greek Salad",
                         "Spanakopita Grilled Cheese",
                         "French Bistro Burger",
                         "Garlic Herb Parmesan Fries",
                         "Marsala Chicken Breast",
                         "Portobello Mushroom Chicken Sandwich",
                         "Shoestring Fries",
                         "Sweet Potato Fries",
                         "Crusty Gruyere Grilled Cheese Sandwich w/ Bacon",
                         "Crusty Gruyere Grilled Cheese Sandwich",
                         "Spanish Style Chorizo Sandwich",
                         "Veggie Burger",
                         "Oven Roasted Garlic Potatoes",
                         "Rice Pilaf",
                         "Roasted Gold & Red Beets",
                         "Roasted Vegetables",
                         "Apple & Cream Cheese Cake",
                         "Brownie w/o Nuts",
                         "Carrot Cake",
                         "Cheesecake",
                         "Chocolate Chip Biscotti",
                         "Chocolate Chip Cookies",
                         "Coconut Cream Pie",
                         "Panna Cotta",
                         "Semolina Blackberry Pear Cake",
                         "Beef & Sweet Potato Soup",
                         "Mushroom Barley Soup",
                         "Southwestern Seafood Soup",
                         "Whole Wheat Linguini w/ Garlic Clam Sauce",
                         "Kale & Squash Salad w/ Gorgonzola",
                         "Kale, Chicken, Currants & Pistachio Salad",
                         "Calypso Bean & Tri-Color Quinoa Taco",
                         "Quinoa",
                         "Pan-Roasted Mushrooms w/ Onions",
                         "Roasted Cauliflower",
                         "Swiss Chard w/ Shallots",
                         "Caramelized Onion, Gouda & White Bean Flatbread",
                         "Tri-Tip, Arugula & Pecorino Flatbread",
                         "Bison Slider w/ Tomato Jam",
                         "Grilled Chicken Breast - Sun Dried Tomato Marinade",
                         "Black Bean & Brown Rice Stacker",
                         "Roasted Red Potatoes",
                         "Blood Oranges",
                         "Grapefruit",
                         "Pineapple",
                         "7 Grain Bread",
                         "Cranberry Walnut Loaf",
                         "Spiced Apple Bread",
                         "Tofu Cranberry Bar",
                         "Whole Wheat Levain Bread",
                         "Almond Cashew Butter",
                         "Cacao Butter",
                         "Peach Vanilla Compote",
                         "Peanut Butter",
                         "Pomegranate & Date Compote",
                         "Blueberries",
                         "Lowfat Greek Yogurt",
                         "Mango",
                         "Orange Pomegranate Water",
                         "Mushroom Barley Soup",
                         "Southwestern Seafood Soup",
                         "Chipotle Chicken Bowl",
                         "Vegan Chipotle Chicken Bowl",
                         "Pork Tacos Al Pastor",
                         "Papa (Potato) Tacos",
                         "Margherita Pizza",
                         "Cheese Pizza",
                         "Pepperoni Pizza",
                         "Chili Cheese Burger",
                         "Smoked Gouda Grill Cheese w/ Mushrooms & Onions",
                         "Bruin Burger",
                         "Bruin Cheeseburger",
                         "White Wine Chicken Breast",
                         "White Wine Chicken Sandwich",
                         "Beet Veggie Burger",
                         "Shoestring Fries",
                         "Turkey Hot Dog",
                         "Grilled Nopales",
                         "Grilled Radishes w/ Lime & Cotija",
                         "Grilled Tri-color Carrots w/ Peruvian Salsa Verde",
                         "Roasted Broccoli",
                         "Apple Crisp",
                         "Brownie w/o Nuts",
                         "Carrot Cake",
                         "Cheesecake",
                         "Chocolate Chip Cookies",
                         "Coconut Cream Pie",
                         "Pumpkin Bake w/ Pecans",
                         "Suspiro Limeno",
                         "Hot & Sour Soup",
                         "Miso Soup",
                         "Seafood Gravy w/ Crispy Noodle",
                         "Malaysian Spicy Honey Vegan Chicken",
                         "Beef Pho Noodle Soup",
                         "Vegetable Pho Noodle Soup",
                         "Green Onion Pancake",
                         "Naan Bread",
                         "BBQ Roast Pork Bao Bun",
                         "Spicy Pork & Vegetable Egg Roll",
                         "Grilled Chicken Thigh",
                         "Teriyaki Chicken Sandwich",
                         "Seared Tofu w/ Spicy Sauce",
                         "Brown Calrose Rice",
                         "Jasmine Rice",
                         "Stir-Fried Noodles & Bean Sprouts",
                         "Brownie w/o Nuts",
                         "Chocolate Cheesecake",
                         "Chocolate Chip Cookies",
                         "Coconut Cream Pie",
                         "Fruit & Tapioca in Cream",
                         "Chinese Cucumber Salad",
                         "Indian Yogurt Dip w/ Herbs & Spices",
                         "Kimchi",
                         "Pickled Bamboo Shoots",
                         "Spicy & Sour Shredded Potatoes",
                         "Spicy Eggplant",
                         "Spicy Sansi",
                         "Spinach w/ Sesame Seeds",
                         "Oatmeal",
                         "Savory Grits",
                         "Chayote, Tri-Tip & Egg Bowl",
                         "Breakfast Fruit Tabbouleh",
                         "Sauteed Pepper & Green Cabbage Frittata",
                         "Red Potato Hash",
                         "Scrambled Egg Whites",
                         "Scrambled Eggs",
                         "Buckwheat Banana-Pecan Waffle",
                         "Wheatgerm Pancake",
                         "Blood Oranges",
                         "Grapefruit",
                         "Kiwi",
                         "7 Grain Bread",
                         "Cranberry Nut Flaxsnax Bread",
                         "Cranberry Walnut Loaf",
                         "Spiced Apple Bread",
                         "Whole Wheat Levain Bread",
                         "Almond Cashew Butter",
                         "Cacao Butter",
                         "Peach Vanilla Compote",
                         "Peanut Butter",
                         "Blueberries",
                         "Cottage Cheese",
                         "Lowfat Greek Yogurt",
                         "Mango",
                         "Strawberry Yogurt",
                         "Orange Pomegranate Water",
                         "Malt-O-Meal",
                         "Oatmeal",
                         "Egg White",
                         "Omelet Bar",
                         "Bacon",
                         "Breakfast Hash Brown",
                         "Chicken Apple Sausage",
                         "Scrambled Eggs",
                         "Fried Eggs",
                         "Belgian Waffle",
                         "Apple Topping",
                         "Blueberry Topping",
                         "Strawberry Topping",
                         "Blueberry Pancakes",
                         "Tator Tots",
                         "Biscuit",
                         "Brown Rice",
                         "Country Gravy",
                         "Alligator Coffee Cake",
                         "Apple Fritter",
                         "Blueberry Muffin",
                         "Chocolate Glazed Donut",
                         "Chocolate Muffin",
                         "Mini Sticky Bun w/ Pecans",
                         "Morning Glory Muffin",
                         "Salvadorian Coffee Cake",
                         "Greek Cream of Roasted Garlic & Cauliflower Soup",
                         "Hearty Italian Soup",
                         "Italian Minestrone Soup",
                         "Rotini w/ Prosciutto & Roasted Peppers",
                         "Rotini Florentine",
                         "Baharat Grilled Chicken",
                         "Traditional Falafel",
                         "Mediterranean Tomato & Cucumber Chopped Salad",
                         "Middle Eastern Artichoke Salad",
                         "Moroccan CousCous Almond Salad",
                         "Moroccan Sweet & Spicy Eggplant",
                         "Baba Ghannouj",
                         "Carrot Harissa Hummus",
                         "Smoked Salmon Mousse",
                         "Tabouli Salad",
                         "Feta Cheese",
                         "Green Pitted Olives",
                         "Kalamata Olives",
                         "Marinated  Olives",
                         "Meatball Pizza",
                         "Cheese Pizza",
                         "Pepperoni Pizza",
                         "Caesar Salad",
                         "Greek Salad",
                         "Spanakopita Grilled Cheese",
                         "French Bistro Burger",
                         "Garlic Herb Parmesan Fries",
                         "Marsala Chicken Breast",
                         "Portobello Mushroom Chicken Sandwich",
                         "Shoestring Fries",
                         "Sweet Potato Fries",
                         "Crusty Gruyere Grilled Cheese Sandwich w/ Bacon",
                         "Crusty Gruyere Grilled Cheese Sandwich",
                         "Spanish Style Chorizo Sandwich",
                         "Veggie Burger",
                         "Oven Roasted Garlic Potatoes",
                         "Rice Pilaf",
                         "Roasted Gold & Red Beets",
                         "Roasted Vegetables",
                         "Brownie w/o Nuts",
                         "Carrot Cake",
                         "Chocolate Cheesecake",
                         "Chocolate Chip Biscotti",
                         "Chocolate Chip Cookies",
                         "Tres Leches Cake",
                         "Mushroom Barley Soup",
                         "Maple Chipotle Pork Tenderloin",
                         "Mushroom & Green Chickpea Risotto",
                         "Mixed Vegetable Flatbread",
                         "Grilled Tilapia w/ Cabbage",
                         "Kiwi",
                         "Pineapple",
                         "Peach Vanilla Compote",
                         "Pineapple Compote",
                         "Smokey Hibiscus Compote",
                         "Spiced Apple Bread",
                         "Cacao Butter",
                         "Mango",
                         "Passion Fruit & Orange Water",
                         "Vegetable Fajitas",
                         "Guava Glazed Pork Ribs",
                         "Chili Cheese Burger",
                         "Smoked Gouda Grill Cheese w/ Mushrooms & Onion",
                         "White Wine Chicken Sandwich",
                         "Beet Veggie Burger",
                         "Shoestring Fries",
                         "Turkey Hot Dog",
                         "Grilled Nopales",
                         "Grilled Tri-color Carrots w/ Peruvian Salsa Verde",
                         "Roasted Broccoli",
                         "Apple Crisp",
                         "Brownie w/o Nuts",
                         "Carrot Cake",
                         "Cheesecake",
                         "Chocolate Chip Cookies",
                         "Coconut Cream Pie",
                         "Pumpkin Bake w/ Pecans",
                         "Suspiro Limeno",
                         "Hot & Sour Soup",
                         "Miso Soup",
                         "Crispy Fried Chicken",
                         "Spicy Chick'n w/ Thai Basil",
                         "Shrimp in Lobster Sauce",
                         "Duk Boggi (Spicy Korean Rice Cake)",
                         "Green Onion Pancake",
                         "Naan Bread",
                         "Black Pepper Steak Bao Bun",
                         "Spicy Pork & Vegetable Egg Roll",
                         "Grilled Chicken Thigh",
                         "Teriyaki Chicken Sandwich",
                         "Seared Tofu w/ Spicy Sauce",
                         "Brown Calrose Rice",
                         "Jasmine Rice",
                         "Stir-Fried Noodles & Bean Sprouts",
                         "Brownie w/o Nuts",
                         "Chocolate Cheesecake",
                         "Chocolate Chip Cookies",
                         "Coconut Cream Pie",
                         "Gulab Jamun",
                         "Kimchi",
                         "Pickled Bamboo Shoots"]

